schema_version = "1.0.0"

id = "renderformer_tools"
version = "1.0.0"
name = "Renderformer Tools"
tagline = "Blender Plugin for RenderFormer Demo"
maintainer = "NCJ <me@ncj.wiki>"
type = "add-on"
blender_version_min = "4.0.0"

website = "https://microsoft.github.io/renderformer/"
tags = ["Import-Export"]

license = [
  "SPDX:MIT",
]

main = "renderformer_tools"

platforms = ["windows-x64", "macos-x64", "macos-arm64", "linux-x64"]
wheels = [
    # platform independent wheels
    "./wheels/bpy_helper-0.0.7-py3-none-any.whl",
    "./wheels/trimesh-4.6.8-py3-none-any.whl",
    "./wheels/networkx-3.4.2-py3-none-any.whl",

    # platform specific wheels
    ## h5py
    "./wheels/h5py-3.13.0-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/h5py-3.13.0-cp311-cp311-macosx_10_9_x86_64.whl",
    "./wheels/h5py-3.13.0-cp311-cp311-win_amd64.whl",
    "./wheels/h5py-3.13.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl",
    ## pymeshlab
    "./wheels/pymeshlab-2023.12.post3-cp311-cp311-macosx_11_0_arm64.whl",
    "./wheels/pymeshlab-2023.12.post3-cp311-cp311-macosx_11_0_x86_64.whl",
    "./wheels/pymeshlab-2023.12.post3-cp311-cp311-win_amd64.whl",
    "./wheels/msvc_runtime-14.42.34433-cp311-cp311-win_amd64.whl",
    "./wheels/pymeshlab-2023.12.post3-cp311-cp311-manylinux_2_31_x86_64.whl",
    ## scipy
    "./wheels/scipy-1.15.2-cp311-cp311-macosx_14_0_arm64.whl",
    "./wheels/scipy-1.15.2-cp311-cp311-macosx_14_0_x86_64.whl",
    "./wheels/scipy-1.15.2-cp311-cp311-win_amd64.whl",
    "./wheels/scipy-1.15.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl"
]
